apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-rescue-backend
  namespace: animal-rescue
spec:
  selector:
    matchLabels:
      app: animal-rescue-backend
  template:
    metadata:
      labels:
        app: animal-rescue-backend
    spec:
      containers:
        - name: animal-rescue-backend
          image: harbor.bearisland.tkg-vsphere-lab.winterfell.life/animal-rescue/animal-rescue-backend:latest
          env:
            - name: spring.profiles.active
              value: k8s
            - name: spring.security.oauth2.resourceserver.jwt.jwk-set-uri
              value: https://dex.castleblack.tkg-vsphere-lab.winterfell.life/keys
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "768Mi"
              cpu: "800m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              initialDelaySeconds: 30
              periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: animal-rescue-backend
  namespace: animal-rescue
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: animal-rescue-backend