apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: animal-rescue-frontend-route-config
  namespace: animal-rescue
spec:
  service:
    name: animal-rescue-frontend
    namespace: animal-rescue
    port: 80
  routes:
    - ssoEnabled: true
      predicates:
        - Path=/rescue/login
        - Method=GET
      filters:
        - StripPrefix=1
        - RedirectTo=302, /rescue
      order: 0
      tags:
        - sso
    - predicates:
        - Path=/rescue/**
        - Method=GET
      filters:
        - StripPrefix=1
      order: 1000
      tags:
        - ui

